version: '3.8'

services:
  springboot-app:
    build: .
    ports:
      - "8080:8080" # Expone el puerto 8080 del contenedor al host
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/mydb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306" # Expone el puerto 3306 para que la aplicación Spring Boot pueda acceder
    volumes:
      - mysql-data:/var/lib/mysql # Persistencia de datos en volumen

volumes:
  mysql-data:
    driver: local