spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://srv939.hstgr.io/u656457449_pruebatecnica?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:u656457449_carlos15}
    password: ${SPRING_DATASOURCE_PASSWORD:Noah1505@}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api